name: Build Workflow

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        
jobs:
  quality_checks:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run unit tests
        run: echo "running unit test"

  package_code:
    name: Package code
    needs: quality_checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: package code
        run: echo "packaging code"

      - run: echo dev > ./dev.txt
      - run: echo ref > ./ref.txt
      - run: echo prod > ./prod.txt

      - uses: actions/upload-artifact@v3
        with:
          name: dev_release
          path: ./dev.txt        

      - uses: actions/upload-artifact@v3
        with:
          name: ref_release
          path: ./ref.txt        

      - uses: actions/upload-artifact@v3
        with:
          name: prod_release
          path: ./prod.txt        
        
  release_dev:
    needs: package_code
    uses: ./.github/workflows/deploy_package.yml
    with:
      ENVIRONMENT_STAGE: dev

  release_ref:
    needs: release_dev
    uses: ./.github/workflows/deploy_package.yml
    with:
      ENVIRONMENT_STAGE: ref

  release_prod:
    needs: release_ref
    uses: ./.github/workflows/deploy_package.yml
    with:
      ENVIRONMENT_STAGE: prod