name: release

on:
    release:
        types: [published]


env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  release_dev:
    uses: ./.github/workflows/sam_release_code.yml
    with:
      TEMPLATE_FILE: dev-${{ github.event.release.tag_name }}-deploy.yaml
      ARTIFACT_BUCKET_PREFIX: ${{ github.event.release.tag_name }}
      STACK_NAME: dev-ci
      TARGET_ENVIRONMENT: dev
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
      
  release_ref:
    needs: [release_dev]
    uses: ./.github/workflows/sam_release_code.yml
    with:
      TEMPLATE_FILE: ref-${{ github.event.release.tag_name }}-deploy.yaml
      ARTIFACT_BUCKET_PREFIX: ${{ github.event.release.tag_name }}
      STACK_NAME: ref-ci
      TARGET_ENVIRONMENT: ref
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.REF_CLOUD_FORMATION_DEPLOY_ROLE }}

  release_qa:
    needs: [release_dev]
    uses: ./.github/workflows/sam_release_code.yml
    with:
      TEMPLATE_FILE: qa-${{ github.event.release.tag_name }}-deploy.yaml
      ARTIFACT_BUCKET_PREFIX: ${{ github.event.release.tag_name }}
      STACK_NAME: qa-ci
      TARGET_ENVIRONMENT: qa
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.QA_CLOUD_FORMATION_DEPLOY_ROLE }}

  release_int:
    needs: [release_qa]
    uses: ./.github/workflows/sam_release_code.yml
    with:
      TEMPLATE_FILE: int-${{ github.event.release.tag_name }}-deploy.yaml
      ARTIFACT_BUCKET_PREFIX: ${{ github.event.release.tag_name }}
      STACK_NAME: int-ci
      TARGET_ENVIRONMENT: int
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.INT_CLOUD_FORMATION_DEPLOY_ROLE }}

  release_prod:
    needs: [release_int]
    uses: ./.github/workflows/sam_release_code.yml
    with:
      TEMPLATE_FILE: prod-${{ github.event.release.tag_name }}-deploy.yaml
      ARTIFACT_BUCKET_PREFIX: ${{ github.event.release.tag_name }}
      STACK_NAME: prod-ci
      TARGET_ENVIRONMENT: prod
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.PROD_CLOUD_FORMATION_DEPLOY_ROLE }}
          
