name: deploy_pr

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml

  get_issue_number:
    runs-on: ubuntu-latest
    needs: quality_checks
    outputs:
      issue_number: ${{steps.get_issue_number.outputs.result}}

    steps:
      - uses: actions/github-script@v6
        name: get issue number
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

  package_code:
    needs: get_issue_number
    uses: ./.github/workflows/package_code.yml
    with:
      TEMPLATE_FILE: PR-${{needs.get_issue_number.outputs.issue_number}}-deploy.yaml
      ARTIFACT_BUCKET_PREFIX: PR-${{needs.get_issue_number.outputs.issue_number}}
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ vars.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}

  release_code:
    needs: [get_issue_number, package_code]
    uses: ./.github/workflows/release_code.yml
    with:
      TEMPLATE_FILE: PR-${{needs.get_issue_number.outputs.issue_number}}-deploy.yaml
      STACK_NAME: PR-${{needs.get_issue_number.outputs.issue_number}}
      ARTIFACT_BUCKET_PREFIX: PR-${{needs.get_issue_number.outputs.issue_number}}
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ vars.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
      TARGET_ENVIRONMENT: dev-pr
