name: release package workflow

on:
  workflow_call:
    inputs:
      STACK_NAME:
        required: true
        type: string
      ARTIFACT_BUCKET_PREFIX:
          required: true
          type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true

jobs:
  release_package:
    runs-on: ubuntu-latest
    environment:  ${{ inputs.TARGET_ENVIRONMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: show environment
        run: |
          echo "TEPMLATE_FILE: ${{ inputs.TEPMLATE_FILE }}"
          echo "STACK_NAME: ${{ inputs.STACK_NAME }}"
          echo "CLOUD_FORMATION_DEPLOY_ROLE: ${{ inputs.CLOUD_FORMATION_DEPLOY_ROLE }}"
          echo "TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}"

