name: tagged_release

on:
  push:
    tags: [v**]

jobs:
  get_release_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

  release_dev:
    needs: get_release_tag
    uses: ./.github/workflows/deploy_package.yml
    with:
      ENVIRONMENT_STAGE: dev

  release_ref:
    needs: release_dev
    uses: ./.github/workflows/deploy_package.yml
    with:
      ENVIRONMENT_STAGE: ref

  release_prod:
    needs: release_ref
    uses: ./.github/workflows/deploy_package.yml
    with:
      ENVIRONMENT_STAGE: prod